CREATE TYPE "sensor_type" AS ENUM ('TEMPERATURE','SOIL_MOISTURE','PH','LIGHT');
CREATE TYPE "crop_status" AS ENUM ('PLANTED','GROWING','HARVEST_READY','HARVESTED','PAUSED');
CREATE TYPE "alert_status" AS ENUM ('OPEN','RESOLVED');