CREATE TABLE "users" (
                         "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         "name" VARCHAR(255) NOT NULL,
                         "email" VARCHAR(255) NOT NULL UNIQUE,
                         "hashed_password" VARCHAR(255) NOT NULL,
                         "profile_picture_url" TEXT,
                         "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
                         "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
