CREATE TABLE "farms" (
                         "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         "user_id" BIGINT NOT NULL REFERENCES users(id),
                         "name" VARCHAR(255) NOT NULL,
                         "size_in_hectares" DECIMAL(10,2),
                         "state" VARCHAR(255) NOT NULL,
                         "city" VARCHAR(255) NOT NULL,
                         "country" VARCHAR(255) NOT NULL,
                         "geolocation" POINT,
                         "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
                         "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         UNIQUE(user_id, name)
);
