CREATE TABLE "crop_types" (
                              "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              "name" VARCHAR(255) NOT NULL UNIQUE,
                              "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                              "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);