CREATE TABLE "crops" (
                         "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         "farm_id" BIGINT NOT NULL REFERENCES farms(id),
                         "crop_types_id" BIGINT NOT NULL REFERENCES crop_types(id),
                         "name" VARCHAR(255) NOT NULL,
                         "planting_date" DATE,
                         "harvest_date" DATE,
                         "status" crop_status NOT NULL DEFAULT 'PLANTED',
                         "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                         UNIQUE (farm_id, name)
);