CREATE TABLE "sensors" (
                           "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           "crop_id" BIGINT NOT NULL REFERENCES crops(id),
                           "name" VARCHAR(255) NOT NULL,
                           "device_uuid" VARCHAR(255) NOT NULL UNIQUE,
                           "type" sensor_type NOT NULL,
                           "status" BOOLEAN NOT NULL DEFAULT true,
                           "last_heartbeat" TIMESTAMPTZ,
                           "install_date" DATE,
                           "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                           "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);