CREATE TABLE "sensor_data" (
                               "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                               "sensor_id" BIGINT NOT NULL REFERENCES sensors(id),
                               "payload" JSONB NOT NULL,
                               "read_at" TIMESTAMPTZ NOT NULL
);