CREATE TABLE "alerts" (
                          "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          "sensor_id" BIGINT NOT NULL REFERENCES sensors(id),
                          "rule_name" VARCHAR(150) NOT NULL,
                          "triggered_value" DECIMAL(10,2) NOT NULL,
                          "message" TEXT NOT NULL,
                          "status" alert_status NOT NULL DEFAULT 'OPEN',
                          "triggered_at" TIMESTAMPTZ NOT NULL,
                          "resolved_at" TIMESTAMPTZ
);
